
model <- load("model_AllIgM.rdata")
p1 <- ggplot(data.frame(y = ranef(model)$k2), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgM(N) normal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_AllIgG.rdata")
p2 <- ggplot(data.frame(y = ranef(model)$b0), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgG(N) normal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_AllIgGS.rdata")
p3 <- ggplot(data.frame(y = ranef(model)$k1), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgG(S) normal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_diseaseIgM.rdata")
p4 <- ggplot(data.frame(y = ranef(model)$k2), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgM(N) ~ Disease severity\nNormal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_diseaseIgG.rdata")
p5 <- ggplot(data.frame(y = ranef(model)$b0), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgG(N) ~ Disease severity\nNormal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_diseaseIgGS.rdata")
p6 <- ggplot(data.frame(y = ranef(model)$k1), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgG(S) ~ Disease severity\nNormal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_genderIgM.rdata")
p7 <- ggplot(data.frame(y = ranef(model)$k2), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgM(N) ~ Gender\nNormal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_genderIgG.rdata")
p8 <- ggplot(data.frame(y = ranef(model)$k2), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgG(N) ~ Gender\nNormal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")
model <- load("model_genderIgGS.rdata")
p9 <- ggplot(data.frame(y = ranef(model)$k1), aes(sample = y))+ stat_qq() + stat_qq_line(fullrange = F)+theme_classic()+ggtitle("IgG(S) ~ Gender\nNormal Q-Q plot")+xlab("Theoretical Quantiles")+ylab("Sample Quantiles")

library(patchwork)
(p1 + p2 + p3)/(p4 + p5 + p6)/(p7 + p8 + p9)
